### PR TITLE
Update to `2.2.0`

### LINKED ISSUE #25: Instagram AJAX Login
The endpoint used in `BasicAuthenticator` appears to be unreachable, either temporarily or, more likely, due to a change in Instagram authentication process.

As for now, please default to `WebViewAuthenticator` for logging in.

### LINKED ISSUE #26: Add response specific types
As of right now, all endpoints return a generic dynamic `ComposableRequest.Response`.\
Going forward I'm going to implement some `protocol`s for the most common responses.

e.g.
```swift
public protocol User
public extension User where Self: DynamicResponse {
     var username: String? { return self["username"].string() }
}
```

### LINKED ISSUE #33: User name and full name from secret key
I can find user identifier in secret likse secret.identitfier.
Is there any option to get user name and full name in secret?

Thanks,
Maria

### LINKED ISSUE #34: Follow and Unfollow doesn't work
Hi Sbertix,
i am using that code for follow and unfollow but they are not working.Can u help?

 
-Unfollow
> Endpoint.Friendship.unfollow(String(userPk))
>         .unlocking(with: secret)
>         .task {
.......
> }

 -Follow
>  Endpoint.Friendship.follow(String(userPk))
>         .unlocking(with: secret)
>         .task {
.......
> }

### LINKED ISSUE #37: Send a request with starting from the specific page
We can pass a page id parameter to the Endpoint class and then our request can start from the specific page. It would be a great feature.

**Example Usage:** 
`Endpoint.Media.comments(for: mediaId, pageId: "XXX")`

### LINKED ISSUE #39: next_max_id issue
In Instagram API, next_max_id doesn't need to be a string all the time. 

This is the example response of `Endpoint.Friendship.followed(by: XXX)` 
```
{
  "sections": null,
  "global_blacklist_sample": null,
  "users": [
      ///
  ],
  "big_list": true,
  "next_max_id": 100,
  "page_size": 200,
  "status": "ok"
}
```

This is the example response of `Endpoint.Friendship.following(XXX)`

```
{
  "sections": null,
  "global_blacklist_sample": null,
  "users": [
     ///
  ],
  "big_list": true,
  "next_max_id": "QVFBd09YWGluX3owcDlVTS1FNUZsc3o4NENwNFdlenB3YlB0T2h0cGZ6bDk5SGR0bXFLSzFsRklpWW1LYXpfX3EwdGo5cGR0ZE51YmU2YUV5NnoydXVseA==",
  "page_size": 200,
  "status": "ok"
}
```

As you can see, next_max_id is can be an integer or a string. Therefore, the library thinks that there is no other page, because of its integer. So, it doesn't send another request for the next page.

Could you fix this issue, please?

### PR DESCRIPTION
**Pull request by sbertix**
## 2.2.0
- [x] Release version renamed from `2.1.1` to `2.2.0` because of breaking changes in paginated `Endpoint`s now always being `func`tions.

### Enhancements
- [x] Add back custom initial page support (closes #37)
- [ ] ~Add response specific types~ (moved to `2.2.1`)
- [ ] ~Add more specificity to `Secret`s~ (moved to `2.2.1`)

### Bugfixes
- [x] Fix #34 
- [x] Fix #39 (thanks to @Goktug)

### CODE REVIEW

**Comment by Goktug** [comment]
@sbertix Thank you for your effort! Is there any idea in your mind regarding when are you going to release this version?

**Comment by sbertix** [comment]
Then I'm gonna release `2.1.2`, with all non-breaking changes and fixes in a couple minutes 💪\
And then I should be done with `2.2.0` by tomorrow or the next day.

**Comment by Goktug** [comment]
You are the man! @sbertix

**Comment by sbertix** [comment]
Change of plans.\
I'm actually merging `2.2.0`, and moving all missing features to `2.2.1`.

**Pull request merged**
